spring.application.name=demo

# 指定监听所有网卡地址，允许外部访问
server.address=0.0.0.0
#server.port=8080   # 默认就是 8080，也可以不改

# PostgreSQL 数据源配置
spring.datasource.url=jdbc:postgresql://localhost:5432/CDQDB
spring.datasource.username=postgres
spring.datasource.password=Ab123456!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 配置
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
##//新版本可以不要这句话
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


debug=true
